name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install hub zip build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-mingw-w64-x86-64

      - name: Debug info
        run: |
          ldd --version
          hub --version
      
